/**
 * Typed content. Everything here is data: the engine interprets it, and adding a card
 * should only ever mean adding data that uses these shapes.
 */

export type Origin = 'Waxborn' | 'Bonebound' | 'Drowned' | 'Bellforged' | 'Beast' | 'Spirit' | 'Pilgrim' | 'Abyssal';
export type Klass = 'Guardian' | 'Marksman' | 'Artillery' | 'Brawler' | 'Reaper' | 'Chanter' | 'Binder' | 'Martyr' | 'Kindler';
export type Trait = Origin | Klass;

export const ORIGINS: readonly Origin[] = ['Waxborn', 'Bonebound', 'Drowned', 'Bellforged', 'Beast', 'Spirit', 'Pilgrim', 'Abyssal'];
export const CLASSES: readonly Klass[] = ['Guardian', 'Marksman', 'Artillery', 'Brawler', 'Reaper', 'Chanter', 'Binder', 'Martyr', 'Kindler'];
export const TRAITS: readonly Trait[] = [...ORIGINS, ...CLASSES];

export type Shape = 'strike' | 'shoot' | 'pierce' | 'cleave' | 'lob' | 'none';
export const SHAPES: readonly Shape[] = ['strike', 'shoot', 'pierce', 'cleave', 'lob', 'none'];

export type Rarity = 'C' | 'U' | 'R';
export type Level = 1 | 2 | 3; // Spark, Flame, Fire

export interface StatLine {
  atk: number;
  hp: number;
  shape: Shape;
}

/** One face-level of a card: its Kindled text and spell at Spark or Flame. */
export interface CardLevelText {
  stats: StatLine;
  text: string;
  spellName: string;
  spellCost: number;
  spellText: string;
}

export interface CardDef {
  id: number;
  name: string;
  rarity: Rarity;
  traits: Trait[];
  icon: string;
  spark: CardLevelText;
  flame: CardLevelText;
  /** Hand-written Fire line, if the pitch gave one. Others are generated by formula (SPEC §10). */
  fireLine?: string;
}

export interface TraitTier {
  n: number;
  text: string;
}
export interface TraitDef {
  kind: 'Origin' | 'Class';
  col: string;
  icon: string;
  what: string;
  tiers: TraitTier[];
}

export interface PositionalRule {
  name: string;
  who: string;
  text: string;
}
export interface Combo {
  name: string;
  traits: Trait[];
  text: string;
  cards: string[];
}
export interface CompCell {
  row: number;
  lane: number;
  card: string;
}
export interface Comp {
  name: string;
  carry: string;
  plan: string;
  flex: string;
  board: CompCell[];
}
export interface WardenDef {
  name: string;
  origin: Origin;
  relic: string;
  deck: number[];
  locked: boolean;
}
export interface RelicDef {
  name: string;
  rarity: 'Common' | 'Uncommon' | 'Rare';
  text: string;
}
export interface EnemyUnitDef {
  id: string;
  name: string;
  atk: number;
  hp: number;
  shape: Shape;
  icon: string;
  text: string;
}
export interface FightDef {
  name: string;
  traits: string;
  lesson: string;
  /** Card names or enemy-unit ids, in scripted play order. */
  deck: string[];
  embers: number;
}
export interface EliteDef {
  name: string;
  traits: string;
  icon: string;
  rule: string;
  counter: string;
  hp: number;
}
export interface BossPhase {
  waves: string;
  name: string;
  text: string;
}
export interface BossDef {
  name: string;
  icon: string;
  hp: number;
  rule: string;
  phases: BossPhase[];
  counter: string;
}
export interface EventDef {
  name: string;
  icon: string;
  flavour: string;
  options: string[];
}
export interface SigilNote {
  term: string;
  text: string;
}

export interface Content {
  version: number;
  cards: CardDef[];
  traits: Record<Trait, TraitDef>;
  positional: PositionalRule[];
  combos: Combo[];
  comps: Comp[];
  sigils: SigilNote[];
  wardens: WardenDef[];
  relics: RelicDef[];
  fireExamples: Record<string, string>;
  enemyUnits: EnemyUnitDef[];
  fights: FightDef[];
  elites: EliteDef[];
  boss: BossDef;
  events: EventDef[];
}
