import type { SpriteDef } from './types';

// Bellforged cards and the drowned city's enemy units. Authored as code per docs/ART.md.
// Legend: p = outline (#181425), '.' = transparent; other characters index the Endesga 32 palette (see palette.ts).
// Bronze ramp 2 (cream highlight) > 3 (bronze) > 1 (copper) > 4/5 (shadow); verdigris d/e; stone k > l > m > n > o.
// Enemies: teal h with navy g shadow, bone k, cyan i wet highlights; the Waxen ones carry amber a.

// c38 Bell Warden: warden behind a bell-shaped shield, mace raised
const c38 = [
  '................................',
  '................................',
  '................................',
  '.................ppp............',
  '...............pp333pp...ppp....',
  '..............p2223333p.p223p...',
  '..............p2223333pp33333p..',
  '..............p3333111pp33313p..',
  '.........pp...poboobo1p.p331p...',
  '........p23p..p3333111p..p5p....',
  '......ppp33p..p3333111p..p5p....',
  '.....p223333p.ppppppppp..p5p....',
  '....p2p33333ppuuuuuvvvvp.p5p....',
  '....p2222222333uuuuvvvvp.p5p....',
  '....p1111111111uuuuvvvvppp5p....',
  '...p223333333puuuuuvvvvvvv5p....',
  '...p2p3333e333uuuuuvvvvvvv5p....',
  '...p2333333333uuuuuvvvvppp5p....',
  '...p2333d333331uuuuvvvvp.p5p....',
  '...p233d3333331uuuuvvvvppvvvp...',
  '..p323333333d311uuuvvvvppvvvp...',
  '..p32333333111111uuvvvvppvvvp...',
  '..p12111111111111uuvvvvp.ppp....',
  '..p23333333333333uuvvvvp........',
  '..p11111111111111uuvvvvp........',
  '...pppppppppppp454pp454p........',
  '..............p444pp444p........',
  '..............p444pp444p........',
  '...............ppp..ppp.........',
  '................................',
  '................................',
  '................................',
];

// c39 Gargoyle: crouched winged gargoyle, stone
const c39 = [
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '.............p.....p............',
  '...p........pkp...plp......p....',
  '..plpp......plpppppmp....ppmp...',
  '...pklppp....plllmmp..pppmmnp...',
  '....pklllpp.pkkllmmmppmmmmnp....',
  '....pklllllppllllmmmmmmmmmnp....',
  '.....pklllllllallmammmmmmnp.....',
  '......pkllllpllllmmmmmmmnp......',
  '......pklllpplpppppmmmmpnp......',
  '.......pkllp.plklkmpmmmnp.......',
  '.......pkllppkllmmmmmmpnp.......',
  '........pkpkkkkkmmmmmmnp........',
  '.........pkkkkkkkmmmmmp.........',
  '.........plkkkkkmmmmmmmp........',
  '.........plllkllmmmmmmmp........',
  '.........pllllllmmmmmmmp........',
  '..........plllllmmmmmmp.........',
  '..........plllllmmmmmmp.........',
  '.........pmmmlllmmmmnnnp........',
  '.........pmmmpppmpppnnnp........',
  '.........pmmmp..p..pnnnp........',
  '......ppppkpkppppppplplpppp.....',
  '.....pmmmmmmmmmmmmmmmmmmmmmp....',
  '.....pnnnonnnnnnnonnnnnnnnnp....',
  '......ppppppppppppppppppppp.....',
  '................................',
  '................................',
];

// c40 Chain Acolyte: tall thin robed acolyte, crossed chains
const c40 = [
  '................................',
  '................................',
  '...............ppp..............',
  '..............pvv4p.............',
  '.............puuv44p............',
  '............pvvvv444p...........',
  '............pvvvv444p...........',
  '...........pvvooooo44p..........',
  '............pvobobo4p...........',
  '............pvooooo4p...........',
  '.............pooooop............',
  '.............pvvv444p...........',
  '............pvvv4444p...........',
  '.........pppkvvv4444kppp........',
  '........pvvvppvv444pp444p.......',
  '........pvvvpvkv44k4p444p.......',
  '........pvvvvvv233444444p.......',
  '........pvvvvvv3p3444444p.......',
  '........pvvvvvv331444444p.......',
  '........pvvvvvkv44k44444p.......',
  '........puuuvpvv444p4uuup.......',
  '........puuukvvv4444kuuup.......',
  '........pkpvvvvv444444pkp.......',
  '.........ppvvvvv444444pp........',
  '........pkpvvvvv444444pkp.......',
  '.........pvvvvvv4444444p........',
  '........pkeeeeeeeeeeee4kp.......',
  '.........pdddddddddddd4p........',
  '..........ppppppppppppp.........',
  '................................',
  '................................',
  '................................',
];

// c41 Tower Archer: archer atop a small stone tower
const c41 = [
  '................................',
  '................................',
  '.............pppp...............',
  '............p4444p..ppp.........',
  '............p4uuup.pk55p........',
  '.............puuvp.pkp5p........',
  '.............pupup.pkp5p........',
  '.............puuupppkp5p........',
  '.............pvvv4kkkk2p........',
  '.............pvvvvuukp5p........',
  '.............pvvvvppkp5p........',
  '.........pp..pvvvvppkp5p........',
  '........pllpplpppmmpk55p........',
  '........pllpplpppmmppnnp........',
  '........poooooooooooooop........',
  '.........plllmmmmmmnnnp.........',
  '.........plllmmmmmmnnnp.........',
  '.........plllmmmmmmnnnp.........',
  '.........plllmammmmnnnp.........',
  '.........plllmammmmnnnp.........',
  '.........plllmmmmmmnnnp.........',
  '.........plllmmppmmnnnp.........',
  '.........plllmppppmnnnp.........',
  '.........plllmoooomnnnp.........',
  '.........plllmoooomnnnp.........',
  '.........plllmoooomnnnp.........',
  '.........plllmoooomnnnp.........',
  '.........plllmoooomnnnp.........',
  '.........plllmoooomnnnp.........',
  '..........pppppppppppp..........',
  '................................',
  '................................',
];

// c42 Cathedral Golem: very broad golem with a rose-window chest
const c42 = [
  '................................',
  '................................',
  '.............pppppp.............',
  '............p233333p............',
  '............pkkmmnnp............',
  '............plmmmnnp............',
  '............pmammanp............',
  '....pppppppppmmmmnnppppppppp....',
  '...p223333333333333333333333p...',
  '...pkkkkkkkkkkkkkkkkkkkkkkkkp...',
  '...plllllmmmmmmmmmmmmmmnnnnnp...',
  '...plllllmmmmmmmmmmmmmmnnnnnp...',
  '...plllllmmmmmmmmmmmmmmnnnnnp...',
  '...plllllmmmmmmmmmmmmmmnnnnnp...',
  '...plllllmmmmmmmmmmmmmmnnnnnp...',
  '...pllmpllmmmm3333mmmmnnpnnnp...',
  '...pllmpllmmm2hhhg3mmmnnpnnnp...',
  '...pllmpllmm2phppgp3mmnnpnnnp...',
  '...pllmpllmm3hhbbgg3mmnnpnnnp...',
  '...pllmpllm3hphaagpg3mnnpnnnp...',
  '...pllmpllmm3hhaagg3mmnnpnnnp...',
  '...pllmpllmm3phppgp3mmnnpnnnp...',
  '...pllmpllmmm3hhhg3mmmnnpnnnp...',
  '..p23333llmmmm3333mmmmnn31111p..',
  '..p33333llmmmmmmmmmmmmnn11111p..',
  '..p33333plmmmmppppnnnnnp11111p..',
  '..p33333plmmmmp..pnnnnnp11111p..',
  '...ppppppmmmmmp..pnnnnnpppppp...',
  '........pmmmmmp..pnnnnnp........',
  '.........ppppp....ppppp.........',
  '................................',
  '................................',
];

// c43 Great Bell: huge bronze bell with a glowing crack, no body
const c43 = [
  '................................',
  '................................',
  '.......pppppppppppppppppp.......',
  '......p444444444444444444p......',
  '......p555555555555555555p......',
  '.......ppppppp2333ppppppp.......',
  '.........ppppp3333ppp...........',
  '........p222333333311p..........',
  '.......p2p33333333311p..........',
  '.....ppp2p33333333311bppppp.....',
  '....p1111111111111111b11111p....',
  '....p222222222222223b333333p....',
  '.....pp2p33333333331a1ppppp.....',
  '......p2p3333d333331b1p.........',
  '.....p2233333333333b111p........',
  '.....p2p33333333333b111p........',
  '.....p2p33d333333331b114p.......',
  '.....p23333d33333331b114p.......',
  '.....p233333333333311bd44p......',
  '.....p23e333333333311b144p......',
  '....p3233333333333311b1444pp....',
  '...p11111111111111111b111111p...',
  '...p4444444444444444b4444444p...',
  '...p3323333333333331ba144444p...',
  '...p3333333333333331b1144444p...',
  '...p3333333333333331b1144444p...',
  '..p11111111111455511111111111p..',
  '..p33333333333555533333333333p..',
  '...ppppppppppp5555ppppppppppp...',
  '..............pppp..............',
  '................................',
  '................................',
];

// c44 Iron Penitent: spiked helm, chained fists
const c44 = [
  '................................',
  '................................',
  '...............p................',
  '............p.pkp.p.............',
  '...........pkpplpplp............',
  '...........plpplppmp............',
  '.........pppllmmmmnnppp.........',
  '........pllpllmmmmnnpmmp........',
  '.........pppllmmmmnnppp.........',
  '...........plo8oo8onp...........',
  '...........pllmmmmnnp...........',
  '.........pppllppppnnppp.........',
  '........pllllllllllllllp........',
  '......pppmmmmmmmmmmnnnnppp......',
  '.....pmmmmmmmmmmmmmnnnnnnnp.....',
  '.....pmmmmmmmnnnnnnooonnnnp.....',
  '.....pmmmmmmmnnnnnnooonnnnp.....',
  '.....pmmmmmm3nn3nn3ooonnnnp.....',
  '....ppmmmmmmmnnnnnnooonnnnpp....',
  '...p223311mmmnnnnnnooo331111p...',
  '...p223311mmmnnnnnnooo111111p...',
  '...p333311mm3nn3nn3ooo111111p...',
  '...p311111mmmnnnnnnooo144441p...',
  '...p333311mmmnnnnnnooo111111p...',
  '...p33331kppuuuuuuuupk111111p...',
  '....pppppplpvvvvvvvvlppppppp....',
  '..........pkmnnppookp...........',
  '...........plnnppolop...........',
  '...........pnklklkoop...........',
  '............pppppppp............',
  '................................',
  '................................',
];

// c45 Belfry Watch: tall thin belfry tower with a lit window
const c45 = [
  '................................',
  '................................',
  '...............p................',
  '..............pkp...............',
  '..............pknp..............',
  '.............pmnnnp.............',
  '............pmnnnnnp............',
  '..........ppmnnnnnnnpp..........',
  '.........poooooooooooop.........',
  '.........popllmoomnnpop.........',
  '..........ppllo33onnpp..........',
  '...........pll2233nnp...........',
  '...........pll3331nnp...........',
  '...........pllo11onnp...........',
  '...........plloooonnp...........',
  '...........pllmmmonnp...........',
  '...........pllmmmmnnp...........',
  '...........pllobbmnnp...........',
  '...........pllbbaannp...........',
  '...........pllaaaannp...........',
  '...........pllaaaannp...........',
  '...........pllaaaannp...........',
  '...........pllaa99nnp...........',
  '...........pllommmnnp...........',
  '..........ppllmmmonnpp..........',
  '.........pllllllllllllp.........',
  '.........plllmmmmmmnnnp.........',
  '.........plllmmmmmmnnnp.........',
  '.........plllmmmmmmnnnp.........',
  '..........pppppppppppp..........',
  '................................',
  '................................',
];

// c46 The Bronze Abbess: serene bronze face and veil, haloed
const c46 = [
  '................................',
  '................................',
  '..............ppppp.............',
  '............ppb22bbpp...........',
  '..........ppbbpppppbbpp.........',
  '.........pbbpp.....ppbbp........',
  '.........pbp.........pbp........',
  '........pbp.ppppppppp.pbp.......',
  '........pappnokkkllooppbp.......',
  '.......pbp.pnkkk3lllop.pbp......',
  '.......pbppnkk22311lloppbp......',
  '.......pbppnk2333111loppbp......',
  '.......pbppkk2333111llppbp......',
  '.......pbpnkkpp33pp1llopbp......',
  '........pbnk333331111lobp.......',
  '........pbnkk3313111llobp.......',
  '........pnnkk3333111lloop.......',
  '........pnnnk33p0p11looop.......',
  '........pnnnkk33311llooop.......',
  '........pnnnnkkk3llloooop.......',
  '.......pnnnnnokkklloooooop......',
  '.......pnnnnnoooooooooooop......',
  '.......pnnnnno22p11oooooop......',
  '......pnnnnnno33p11ooooooop.....',
  '......pnnnnnno33p11ooooooop.....',
  '......pnnnnnno33p11ooooooop.....',
  '.....pnnnnnnnoooooooooooooop....',
  '.....pnnnnnnnoooooooooooooop....',
  '......ppppppppppppppppppppp.....',
  '................................',
  '................................',
  '................................',
];

// c47 Bellfounder Titan: towering titan with a gong, red core
const c47 = [
  '................................',
  '................................',
  '..............p......p..........',
  '.............p2p....p3p.........',
  '.............p3pppppp1p.........',
  '..............p445566p..........',
  '..............p455566p..........',
  '..............p58oo86p..........',
  '.........pppppp555566pppppp.....',
  '........p444444444444444444p....',
  '........p555555555555566666p....',
  '........p555555555555566666p....',
  '........p555555555555566666p....',
  '.......p44444475555756666666p...',
  '.......p44444457555556666666p...',
  '.......p44444455588556666666p...',
  '......pp444444558ba856666666p...',
  '.....p22111444558a8856666666p...',
  '....p21333314455588556666666p...',
  '....p23111131455555576666666p...',
  '....p131b3131455755557666666p...',
  '...p1313aa3131555555566665555p..',
  '....p131331314555555566665555p..',
  '....p131111315666pp6666pp5555p..',
  '.....p133331p5666pp6666p.pp5p...',
  '......p1111pp6666pp6666p.pp5p...',
  '.......pppp.p6666pp6666ppllnnp..',
  '............p6666pp6666ppnnnnp..',
  '............p6666pp6666ppnnnnp..',
  '.............pppp..pppp..pppp...',
  '................................',
  '................................',
];

// c48 The Silent Bell: cracked dark bell, broken clapper, slate
const c48 = [
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '.............pppp...............',
  '............plmmnp..............',
  '.........p.ppmmmnpp.............',
  '........plpmmmmmnnnp............',
  '.......plpmmpmmmnnnp............',
  '......pplpmmpmmmnnnppppp........',
  '.....plllllllollmmmmmmmmp.......',
  '.....pooooooopoooooooooop.......',
  '......plpmmmmpmmnnnnpppp........',
  '......plpmmmpmmmnnnnp...........',
  '.....pllmmmpmmmmnnnnop..........',
  '.....plpmmmpommmnnnnop..........',
  '.....plmmmpmmmmmnnnnoop.........',
  '.....plmmmpmmmmmnnnnoop.........',
  '.....plmmmpmmmmmnnnnooop........',
  '....pmlmmmpommmmnnnnoooop.......',
  '....poooooopooooooooooop........',
  '....pmmmmmmpmmmmnnnnoop.........',
  '....pmmmmmmpmmmmnnnnoop.........',
  '....pnnnnnnpnnnnnnnnppop.ppp....',
  '.....pppppp.pppppppp..poplmmp...',
  '.......................pmmmmmp..',
  '.......................pmmmmnp..',
  '........................pmmnp...',
  '.........................ppp....',
  '................................',
  '................................',
];

// c58 Rubble Golem: lumbering pile of stones with glowing eyes
const c58 = [
  '................................',
  '................................',
  '................................',
  '............p...................',
  '..........pplpp.................',
  '.........pkklllpp....p..........',
  '........plkllllllppppmpp........',
  '.........plllllllllmllmmp.......',
  '..........pplllllllmlmmmp.......',
  '...........plllllllmmmmmp.......',
  '..........pllllllllllmpp........',
  '...........plllllllllp..........',
  '...........ploaaooaaop..........',
  '..........pppoooooooop....p.....',
  '.........plllmmmpmmmmmp..pnp....',
  '.....ppppkklllmmmpmmmmmppmmnp...',
  '....pllllklllllmmmmmmmmpnmnnnp..',
  '...plkkllllllllmmmmmmommnnnnnp..',
  '...plklllllllllmmmmmmmmmnnnnnp..',
  '...pllllllllllmmmmmmmmmmpooop...',
  '....pmmmpppllmmmmmmmmmmponnoop..',
  '...pmllmmpmpmmmmmmmpmmmponooop..',
  '...pmlmmmmmmpmmmmmmmppppooooop..',
  '...pmmmmmmmmmpmmmmmmnnpnpooop...',
  '....pmmmmmmmmmnmnnnnnnnnmmmp....',
  '....pmmmmmmmmmnnnnnnnnnmllmmp...',
  '.....pmmmommmmnnnnnnnnnmlmmmp...',
  '.....pmmmmmmmmmnnnnnnnnmmmmmp...',
  '.....poooooooooooooooooooooop...',
  '......pppppppppppppppppppppp....',
  '................................',
  '................................',
];

// e_sentry Drowned Sentry: waterlogged spear sentry
const e_sentry = [
  '................................',
  '................................',
  '........p.......................',
  '.......pkp......................',
  '.......pkp....ppppppp...........',
  '......pkkkp..p1111177p..........',
  '......pkkkp..p1000077p..........',
  '.......plp...p0000077p..........',
  '.......p5p...phhhhhggp..........',
  '.......p5p...phkkhkggp..........',
  '.......p5p...phphhpggp..........',
  '.......p5p...phhhhhggp..........',
  '.......p5ppppiiiiiigggppp.......',
  '.......p5phhphhhhhhgggpggp......',
  '.......p5phhphhhphhgggpggp......',
  '.......p5phhphkkpkhgggpggp......',
  '.......p5phhphhhphhgggpggp......',
  '.......p5phhphkkpkhgggpggp......',
  '.......p5phhphhhphhgggpggp......',
  '.......p5phhphkkpkhgggpggp......',
  '.......p5pkkkhhhphhgggpggp......',
  '.......p5pkkkhhhhhhgggkkkp......',
  '.......p5ppppphggpgggpkkkp......',
  '.......p5ppipphggpgggppppip.....',
  '.......p5p.p.pgggpgggp..php.....',
  '.......p5p...pgggpgggp...p......',
  '.......p5p...pgggpgggp..........',
  '.......p5p...pgggpgggp..........',
  '.......p5p...pgggpgggp..........',
  '........p.....ppp.ppp...........',
  '................................',
  '................................',
];

// e_hook Tide Hook: hunched figure with a big hook
const e_hook = [
  '................................',
  '................................',
  '................................',
  '................................',
  '..........................p.....',
  '.........................pkp....',
  '.........................pllp...',
  '.........................plmp...',
  '...........ppppp.........plmp...',
  '.........ppgggggpp.......plmp...',
  '........pighggggggp......plmp...',
  '.......pihhhhhgggggp.....plmp...',
  '......pghhhhhhhgggggp....plmp...',
  '.....pghhhhhhhhhgghhgp...plmp...',
  '.....pghhhhhhhhhghhhggp..plmp...',
  '.....pghhhhhhhhhhhhkgkgp.plmp...',
  '.....pgghhhhhhhghhhpgpgp.plmp...',
  '.....pggghhhhhgghhhhgggppplmp...',
  '......pgggghggggghhppppphhhhp...',
  '.......pggggggggghhhhhgghhhgp...',
  '........pggggggggggggggghhhgp...',
  '.......phgggggggggggggggpplmp...',
  '.......phggpppgggppppmpp.plp....',
  '.......pgggp.pgggp...plppplp....',
  '.......pgggp.pgggp....plllp.....',
  '.......pgggp.pgggp....pmmp......',
  '.......pgggp.pgggp.....pp.......',
  '.......pgggp.pgggp..............',
  '......pggggp.pggggp.............',
  '.......pppp...pppp..............',
  '................................',
  '................................',
];

// e_salthound Salt Hound: crusted white-grey hound, low and long
const e_salthound = [
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '...........................p....',
  '........pp.....p..........pkp...',
  '......ppkkp.p.pjp..p..p....plp..',
  '.....pkkklkpjppkpppkpplp...plp..',
  '....pkkhkkkkpkkkkkkkkkppp.plp...',
  '...pkkkkkkkkkkkkkllllllllpplp...',
  '....plkkkkkkkkkkkllllllllllp....',
  '.....pppkkkkkkkkkllllllllllp....',
  '.....pkpkkkkkkkkkllllllllllp....',
  '......ppkkkkkkkkkllllllllllp....',
  '........pkkkkkkkklllllllllp.....',
  '.........pgggggggggggggggpp.....',
  '.........pllpkkggggggllppkkp....',
  '.........pllpkkppppppllppkkp....',
  '.........pllpkkp....pllppkkp....',
  '.........pllpkkp....pllppkkp....',
  '.........pllpkkp....pllppkkp....',
  '.........pglpggp....pglppggp....',
  '..........pp.pp......pp..pp.....',
  '................................',
  '................................',
  '................................',
];

// e_chorister Chorister: small hooded singer, open mouth, sound rings
const e_chorister = [
  '................................',
  '................................',
  '................................',
  '..............p.................',
  '.............php................',
  '.............php................',
  '............phgp................',
  '............phgp........p.......',
  '...........phggnp......php......',
  '...........phggnpp...p..php.....',
  '..........pooooooop.pip.pip.....',
  '.........pgoioooiop..pip.pip....',
  '.........phooooooop..pip.pip....',
  '........pghoop7poonppip.pip.....',
  '........phgoopppoonp.p..php.....',
  '.........ppggggnnnp....php......',
  '..........pggggnnnp.....p.......',
  '..........pggggnnnp.............',
  '.........pgggggnnnnp............',
  '.........pgggggnnnnp............',
  '.........pggkkpkknnp............',
  '.........pggkkkklnnp............',
  '........pgggkkkklnnnp...........',
  '........pggggggnnnnnp...........',
  '........pggggggnnnnnp...........',
  '........pggggggnnnnnp...........',
  '........pooooooooooonp..........',
  '.........pppppppppppp...........',
  '................................',
  '................................',
  '................................',
  '................................',
];

// e_shambler Shambler: slumped bloated walker
const e_shambler = [
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '......................ppp.......',
  '.....................phhgp......',
  '....................phhhggp.....',
  '................p..phhhhgggp....',
  '............pppphpppggohgogp....',
  '..........pphhhhhggggghhgggp....',
  '.......ppphhhhhhhgggggppppp.....',
  '......phhphiihhhhggggghkgpp.....',
  '......phhpihhhhhhgkkggggpggp....',
  '......phhphhhhhhhgggggggpggp....',
  '......phhphhhhhhhgkkggggpggp....',
  '......phhphhhhhhhgggggggpggp....',
  '......phhphhhhghhgggggggpggp....',
  '......phhphhhhhghgggggggpggp....',
  '......phhphhhghhhgggggggpggp....',
  '......phhphhhhhhhggggggppggp....',
  '......phhpphhhhhhgggggp.pggp....',
  '......phhp.pggghhggggp.pkkkp....',
  '......pkkkpphggphpgggp.pkkkp....',
  '......pkkkpphggpppgggp..ppp.....',
  '.......ppp.pgggp.pgggp..........',
  '...........pgggp.pgggp..........',
  '............ppp...ppp...........',
  '................................',
  '................................',
];

// e_thief Candle Thief: sneaky crouched figure clutching a stolen candle
const e_thief = [
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '..............p.................',
  '............ppgpp...............',
  '...........phhhnnp..............',
  '..........pggggnnnp.............',
  '..........pggggnnnp.............',
  '.........pgokkokonnp............',
  '..........popooponp.............',
  '..........poooooonp..p..........',
  '...........pgggnnp..pap.........',
  '..........ppgggnnpppabap........',
  '.........phggggnnnnpabap........',
  '........phgggggnnnnnp9p.........',
  '.......pghhhhggnnnnnnpp.........',
  '.......pgggggggnnnnn2kkp........',
  '.......pgggggggnnnnnkklp........',
  '.......pgggggggnnnkkkkkpp.......',
  '.......pgggggggnnnkkkklllp......',
  '........pggggggnnnkkkkkllp......',
  '........pggggggnnnnpkklllp......',
  '........pggggggnnnnnkkkpp.......',
  '........pgggpppppnnnkkkp........',
  '........pgggp...pnnnppp.........',
  '........pgggp...pnnnpp..........',
  '.......pgggggp..pnnnnnp.........',
  '........ppppp....ppppp..........',
  '................................',
  '................................',
];

// e_waxen Waxen Effigy: melted wax figure, drippy, wick lit
const e_waxen = [
  '................................',
  '................................',
  '................p...............',
  '...............pbp..............',
  '..............pabap.............',
  '..............paaap.............',
  '..............p9a9p.............',
  '..............pp2pp.............',
  '.............p222uup............',
  '............pjj22uuup...........',
  '...........p22222uuuup..........',
  '...........p22o22uouup..........',
  '...........p22o22uouup..........',
  '............p2222ugup...........',
  '............pp2gggupp...........',
  '.........ppp22222uuuuppp........',
  '........p2222jj22uuuuuuup.......',
  '........p22222222uuuuuuup.......',
  '........p22222222uuuuuuup.......',
  '........p222g2222uuuuuuup.......',
  '........p22222222uuuguuup.......',
  '........p22222222uuuuuuup.......',
  '........p2u2222g2uuuuuuup.......',
  '........p22222222uuuu333p.......',
  '........pu2222222uuuu3333p......',
  '.......ppppppuppupp3ppp3p.......',
  '......p222222uuuu3333333ppp.....',
  '.....puuuuuuuuuuu3333333333p....',
  '......pppuuuuuuuu3333333ppp.....',
  '.........ppppppppppppppp........',
  '................................',
  '................................',
];

// e_ghoulbell Bell Ghoul: gaunt ghoul with a bell on a chain round its neck
const e_ghoulbell = [
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '.............ppppppp............',
  '............piihhhggp...........',
  '............phhhhhggp...........',
  '............phkohkogp...........',
  '............phoohoogp...........',
  '............phhhhhkgp...........',
  '............phpkpkpgp...........',
  '.......pp..plplphplplp..pp......',
  '......phhpphhhhhlhggggppggp.....',
  '......phhpphkkkkphggggppggp.....',
  '......phhpphhhh231ggggppggp.....',
  '......phhpphkkk331ggggppggp.....',
  '......phhpphhh23311gggppggp.....',
  '......phhpphkk33311gggppggp.....',
  '......phhpphhh33311gggppggp.....',
  '......phhpphhh11511gggppggp.....',
  '......phhpphhhhhhhggggppggp.....',
  '......phhp.phhgpppgggp.pggp.....',
  '......phhgpphhgp.pgggp.pggp.....',
  '.....pklklkphhgp.pgggppgggp.....',
  '......pppppphhgp.pgggpklklkp....',
  '...........phhgp.pgggpppppp.....',
  '...........phhgp.pgggp..........',
  '..........pggggp.pggggp.........',
  '...........pppp...pppp..........',
  '................................',
  '................................',
];

// e_crab Belfry Crab: big crab with a little belfry on its shell
const e_crab = [
  '................................',
  '................................',
  '................p...............',
  '...............pkp..............',
  '..............pnmpp.............',
  '.............pmmnnnp............',
  '............pmnnnnnnp...........',
  '............pooooooop...........',
  '.............plmmmnp............',
  '.............pl233np............',
  '.............pl331np............',
  '.............plo1onp............',
  '....pp.......plooonp.......pp...',
  '...phhp.....pplmmmnpp.....pggp..',
  '...phhppp..pkplmomnpkp..pppggp..',
  '....piihhp.pgplommnpgp.pggggp...',
  '....phhhhpppgplmmmnpgp.pggggp...',
  '....phphhphhhhhhhggggnppggpgp...',
  '....phhhhiiihhhhhhhggnnnggggp...',
  '....pgggghhhhhhhhhhggnnnnnnnp...',
  '.....ppghhhhhhhhhhhggnnnnnpp....',
  '.....pgggghhhhhhhggggnnnnngp....',
  '.....pgggggggggggggggnnnnngp....',
  '....pgppggggnggggggngnnnnppgp...',
  '....pgpgpgggggggnggggnnnpnpgp...',
  '...pgpgp.ppggggggggggnpp.pgpgp..',
  '...pnpgp...pppppgppppp...pgpnp..',
  '....pgp.........p.........pgp...',
  '....pnp...................pnp...',
  '.....p.....................p....',
  '................................',
  '................................',
];

export const bellforgedSprites: SpriteDef[] = [
  { id: 'c38', rows: c38 },
  { id: 'c39', rows: c39 },
  { id: 'c40', rows: c40 },
  { id: 'c41', rows: c41 },
  { id: 'c42', rows: c42 },
  { id: 'c43', rows: c43 },
  { id: 'c44', rows: c44 },
  { id: 'c45', rows: c45 },
  { id: 'c46', rows: c46 },
  { id: 'c47', rows: c47 },
  { id: 'c48', rows: c48 },
  { id: 'c58', rows: c58 },
  { id: 'e_sentry', rows: e_sentry },
  { id: 'e_hook', rows: e_hook },
  { id: 'e_salthound', rows: e_salthound },
  { id: 'e_chorister', rows: e_chorister },
  { id: 'e_shambler', rows: e_shambler },
  { id: 'e_thief', rows: e_thief },
  { id: 'e_waxen', rows: e_waxen },
  { id: 'e_ghoulbell', rows: e_ghoulbell },
  { id: 'e_crab', rows: e_crab },
];
