import type { SpriteDef } from './types';

/**
 * Drowned Origin sprites (cards 25–36, 53, 54) and the shared tokens.
 * Legend: p outline · h teal · i cyan · g navy · f deep teal · k bone · j white · u sand · v tan
 * d moss · e pine · c green · s mauve · r plum · m slate · n indigo · l steel · 8 red · 7 blood.
 * Light comes from the top-left; the board behind the sprite is deep teal (#193c3e).
 */

// c25 Drowned Archer: a waterlogged archer drawing a long bone bow, arrow nocked at the chest.
const drownedArcher = [
  '................................',
  '................................',
  '................................',
  '.............ppppp..............',
  '............phhhhhp.............',
  '...........phiihhhhp............',
  '...........phhhhhhhp............',
  '...........pggggggp.............',
  '......p....pgigiggp.............',
  '.....pkp...pggggggp.............',
  '.....pkpj..ppgggpp..............',
  '....pkp.j..phhhhhp..............',
  '....pkp..j.phhihhhgp............',
  '...pkp...jphhihhhhhgp...........',
  '...pkp....jhhhhhhhhgp...........',
  '..pkp.....phhhhhhhhgp...........',
  '..lkpuuuuuuuhhhhhhhgp...........',
  '..pkphhhhhhhhhhhhhhgp...........',
  '..pkpppppjphhhhhhhgp............',
  '...pkp...j.pghhhhhgp............',
  '...pkp..j..pgghhhggp............',
  '....pkp.j..pggghhggp............',
  '....pkpj...pggggggp.............',
  '.....pkp...pggp.pggp............',
  '......p....pggp.pggp............',
  '...........pggp.pggp............',
  '...........pggp.pggp............',
  '..........pgggp.pgggp...........',
  '..........ppppp.ppppp...........',
  '................................',
  '................................',
  '................................',
];

// c26 Moray: a long eel coiled in an S, head top-left with the jaw open.
const moray = [
  '................................',
  '................................',
  '................................',
  '......pppppp....................',
  '.....pgiihhhpp..................',
  '....pgihhhhhhhpppppppp..........',
  '...pgiihhhhhhhhhhhhhhhppp.......',
  '...pghjphhhhhhhhhhhhhhhhhpp.....',
  '...pghpphhhhhhhhhhhhhhhhhhhp....',
  '...pghhhhhhhhpppphhhhhhhhhhp....',
  '...ppjpjpjppp....pphhhhhhggp....',
  '....p.p.p..........pphhhhhgp....',
  '...pjpjpjpp.........phhhhhgp....',
  '...pghhhhhhpp.......phhhhhgp....',
  '....pgghhhhhppppppppphhhhggp....',
  '.....ppgghiihhhhhhhhhhhhhggp....',
  '.......ppghhhhhhhhhhhhhggpp.....',
  '......ppghhhhhhhhhhhhhggpp......',
  '.....pgihhhhhhhhhhhhhggpp.......',
  '....pgihhhhhhpppppppppppp.......',
  '....pghhhhhpp...................',
  '....pghhhgp.....................',
  '....pghhhgpp....................',
  '....pghhhhhpppppppppp...........',
  '.....pghiihhhhhhhhhhhhppp.......',
  '......ppghhhhhhhhhhhhhhhpp......',
  '........pppgghhhhhhhhhhhhhp.....',
  '...........ppppggghhhhhhhip.....',
  '..............pppppppppppp......',
  '................................',
  '................................',
  '................................',
];

// c27 Kelp Wraith: a tall hooded figure made of trailing kelp strands.
const kelpWraith = [
  '................................',
  '................................',
  '.............ppp................',
  '............pcddp...............',
  '...........pcdddep..............',
  '...........pdddddp..............',
  '...........pdddddep.............',
  '..........pddididdep............',
  '..........pdddddddep............',
  '..........pedddddeep............',
  '.........pdcddddddeep...........',
  '.........pdhddddddeep...........',
  '........pddhddddddeeep..........',
  '........pdhdddhdddddeep.........',
  '.......pddhdddhdddhddeep........',
  '.......pdhdddhddddhdeeeep.......',
  '......pddhdddhdddhdddeeeep......',
  '......pdhdddhhdddhdddeeeeep.....',
  '.....pddhdddhdddhhddddeeeep.....',
  '.....pdhddddhddddhdddeeeeep.....',
  '....pddhdddhhdddhhdddeedeeep....',
  '....pdhdpddhdpddhddpdedpeeep....',
  '....pdhppdhdppdhhdpphdppeeep....',
  '....pdpppdhpppdhhpppdpppeepp....',
  '...pdhp.pdhp..phhp..pdp.pep.....',
  '...pdp..pdp...php...php.pep.....',
  '...pdp..php...pep...pdp.pdp.....',
  '....pp..pep....pp...pep..pp.....',
  '........pp..........pp..........',
  '................................',
  '................................',
  '................................',
];

// c28 Pearl Diver: a crouched diver, arm raised, holding up a glowing pearl.
const pearlDiver = [
  '................................',
  '................................',
  '................................',
  '........ppp.....................',
  '.......pijjp....................',
  '.......pjjjjp...................',
  '.......pijjip...................',
  '........pipp....................',
  '........puup....................',
  '........puup....................',
  '........puup........pppp........',
  '.........puup......puuuup.......',
  '.........puup.....puuuuuup......',
  '..........puup....pggggggp......',
  '..........puup....pgigigvp......',
  '...........puup...puuvuuvp......',
  '...........puuppppuuvvuvp.......',
  '............puuuuuuuvvvp........',
  '...........puuuuuuuuuvvvp.......',
  '..........puuuuuuuuuuvvvvp......',
  '.........puuuhhhhhhhuuvvvvp.....',
  '........puuuhhhhhhhhhuuvvvvp....',
  '........puuphhhhhhhhhhpuvvvvp...',
  '........puupghhhhhhhhgpuuvvvp...',
  '........puupgghhhhhhggpuuvvvp...',
  '.........pupppgggggpppuuuvvp....',
  '.........puup.......puuuvvvp....',
  '..........pppp......pppppppp....',
  '................................',
  '................................',
  '................................',
  '................................',
];

// c29 Barnacle Thrall: a squat, wide hulk crusted in barnacles, head sunk between the shoulders.
const barnacleThrall = [
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '.............pppppp.............',
  '............pghhhhgp............',
  '............pgiggigp............',
  '............pghhhhgp............',
  '.......pppppphhhhhhpppppp.......',
  '.....ppgiihhhhhhhhhhhhhhhgpp....',
  '....pghhhhk2hhhhhhhhk2hhhhggp...',
  '...pghhk2hhhhhhk2hhhhhhhkhhggp..',
  '...pghhhhhhhhhhhhhhhhhhhhhhhgp..',
  '...pghhk2hpppppppppppphhhhk2gp..',
  '...pghhhhhpghhk2hhhhhhphhhhhgp..',
  '...pghhhhhpghhhhhhk2hhphhk2ggp..',
  '...pghk2hhpghhhhhhhhhhpghhhhgp..',
  '...pghhhhhpgghk2hhhhhhpgghhhgp..',
  '...pgghhhkpgghhhhhk2ggpgghhggp..',
  '...pggghhhpggghhhhhgggpggghggp..',
  '...pppppppggghhhhhhgggppppppp...',
  '.........pgggghhhhggggp.........',
  '.........pgggp.pppgggp..........',
  '.........ppppp....pppp..........',
  '................................',
  '................................',
  '................................',
];

// c30 Brine Choir: two floating drowned singers, mouths open in a hymn.
const brineChoir = [
  '................................',
  '................................',
  '................................',
  '................................',
  '.......pppp.....................',
  '......psjssp....................',
  '.....psjssssp...................',
  '.....pssssssp.......pppp........',
  '.....psisissp......psjssp.......',
  '.....pssssssp.....psjsssrp......',
  '.....pssjjssp.....pssssssp......',
  '.....psspjpsp.....psisissp......',
  '.....pssppssp.....pssssssp......',
  '.....psssssrp.....pssjjssrp.....',
  '.....psssssrp.....pssspjpsp.....',
  '....pssssssrrp....pssspppsp.....',
  '....pssssssrrp....psssssrrp.....',
  '....pssssssrrp...pssssssrrrp....',
  '....pssssssrrp...pssssssrrrp....',
  '....psssssrrrp...pssssssrrrp....',
  '.....psssrrrp....pssssssrrrp....',
  '.....pssrpsrp....psssssrrrrp....',
  '......pspprp......pssssrrrp.....',
  '......pp..pp......pssrpsrrp.....',
  '..................psrp.prrp.....',
  '..................ppp..ppp......',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
];

// c31 Siren of Vael: a seated siren, long hair streaming right, fish tail coiled to the left.
const sirenOfVael = [
  '................................',
  '................................',
  '................................',
  '.............ppppp..............',
  '............pggghhp.............',
  '...........pgghhhhhp............',
  '...........pguuuugghp...........',
  '..........pguuiuuugghp..........',
  '..........pguuuuuugghp..........',
  '..........pgpuuuupgghp..........',
  '...........ppuuupgghhp..........',
  '............puupghhhhhp.........',
  '...........puuuupghhhhp.........',
  '..........puuuuuupghhhhp........',
  '.........puuuuuuupghhhhp........',
  '........puupuuuuuhpghhhp........',
  '.......puup.puuuhhhpghhp........',
  '.......puup..phhhhhhphhp........',
  '.......ppp...phhhhhhhhhhp.......',
  '............phihhhhhhhhhhp......',
  '..........pphihhhhhhhhhhhhp.....',
  '........pphhihhhhhhhhhhhggghp...',
  '......pphhhhhhhhhhhhhhhhhhhggp..',
  '....pphhiihhhhhhhhhhhhhhhhhhgp..',
  '...phhiihhhhpppppphhhhhhhhhgp...',
  '...pphhhhhpp......ppphhhhhpp....',
  '....ppppppp..........ppppp......',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
];

// c32 Rot Priest: a beaked plague-doctor in profile, wide hat, sand robe, bone staff.
const rotPriest = [
  '................................',
  '................................',
  '...........pppppppp.............',
  '..........pgggggggggp...........',
  '...pppppppgggggggggggppppp......',
  '..pgggggggggggggggggggggggp.....',
  '..pppppppkkkkkkkpppppppppp......',
  '......ppkkkkkkkkpuup.....ppp....',
  '....ppkkkkkkpipkpuuup....pkkp...',
  '...pkkkkkkkkpppkpuuuup...pkp....',
  '..pkkkkkkkkkkkkpuuuuuup..pkp....',
  '..ppppppkkkkkkpuuuuuuup..pkp....',
  '........ppppppppuuuuuuup.pkp....',
  '..............puuuuuuuuupkp.....',
  '.............puuuuuuuvvupkp.....',
  '.............puuuuuuuvvvpkp.....',
  '............puuuuuuuuvvvpkp.....',
  '............puuuuuuuuvvvvpkp....',
  '...........puuuuuuuuuvvvvpkp....',
  '...........puuuuuuuuuvvvvpkp....',
  '..........puuuuuuuuuuuvvvvpkp...',
  '..........puuuuuuuuuuuvvvvpkp...',
  '.........puuuuuuuuuuuuvvvvpkp...',
  '.........puuuuuuuuuuuuvvvvvpkp..',
  '........puuuuuuuuuuuuuvvvvvpkp..',
  '........puuuuuuuuuuuuuvvvvvpkp..',
  '........puuuuuuuuuuuuuuvvvvpkp..',
  '........pppppppppppppppppppppp..',
  '..........................pkp...',
  '..........................ppp...',
  '................................',
  '................................',
];

// c33 Gloom Jelly: a round jellyfish, cyan-lit bell, tentacles trailing below.
const gloomJelly = [
  '................................',
  '................................',
  '................................',
  '...........pppppppppp...........',
  '.........pphiihhhhhhhpp.........',
  '........phiiihhhhhhhhhhp........',
  '.......phiihhhhhhhhhhhhhp.......',
  '......phihhhhhhhhhhhhhhhhp......',
  '......phhhhhhhhhhhhhhhhhhp......',
  '.....phhhhhhjhhhhhhjhhhhhhp.....',
  '.....phhhhhhhhhhhhhhhhhhhhp.....',
  '.....pghhhhhhhhhhhhhhhhhggp.....',
  '.....pgghhhhhjhhhhhhhhhgggp.....',
  '......pggghhhhhhhhhhhggggp......',
  '......ppgggggggggggggggggp......',
  '......ppipipiipipipiipipipp.....',
  '......phphp.php.phphp.phphp.....',
  '......phphp.php.phphp.phphp.....',
  '.......php..php..php...php......',
  '.......php..php..php...php......',
  '.......pip..php..php...pip......',
  '........php.pip..pip..php.......',
  '........php..php.php..php.......',
  '.........php.php..php.php.......',
  '.........pip.pip..pip..pip......',
  '.........pp..php..php..pp.......',
  '.............pp....pp...........',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
];

// c34 Leviathan Calf: a small whale, big and wide, pale belly, red eye.
const leviathanCalf = [
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '.........ppppppppppp............',
  '......pppgggggggggggppp.........',
  '....ppggghhhhgggggggggggp.......',
  '...pgggghhhhhhhggggggggggp..pp..',
  '..pggghhhhhhhhhhhggggggggp.pgp..',
  '..pghp8phhhhhhhhhhggggggggpgp...',
  '..pghpppphhhhhhhhhhhhggggggggp..',
  '..pghhhhhhhhhhhhhhhhhhhhhgggp...',
  '..pghhhhhhhhhhhhhhhhhhhhhhhhp...',
  '..pghhhhhhhhhhhhhhhhhhhhhggggp..',
  '..pgkkkkhhhhhhhhhhhhhhhhgppggp..',
  '..pgkkkkkkkkhhhhhhhhhhhgp..pgp..',
  '..pgkkkkkkkkkkkkhhhhhhhhp...pp..',
  '...pkkkkkkkkkkkkkkkhhhhp........',
  '...plkkkkkkkkkkkkkkkkkp.........',
  '....plkkkkkkkkkkkkkkkp..........',
  '.....pllkkkkkkkkkkkkp...........',
  '......ppllkppkkllpp.............',
  '........pppphhpppp..............',
  '...........phhp.................',
  '...........pppp.................',
  '................................',
  '................................',
  '................................',
  '................................',
];

// c35 Mother of Silt: an octopus crowned with silt, plum underside, arms spread.
const motherOfSilt = [
  '................................',
  '................................',
  '..........p...p...p...p.........',
  '.........pup.pup.pup.pup........',
  '........ppuuppuuppuuppuup.......',
  '.......puuuuuuuuuuuuuuuuup......',
  '.......pghhhhhhhhhhhhhhhgp......',
  '......pghiihhhhhhhhhhhhhhgp.....',
  '......phihhhhhhhhhhhhhhhhhgp....',
  '.....phihhhhhhhhhhhhhhhhhhgp....',
  '.....phhhhhhhhhhhhhhhhhhhhgp....',
  '.....phhhhhpiphhhhhhpiphhhgp....',
  '.....phhhhhpppphhhhhppphhhgp....',
  '.....pghhhhhhhhhhhhhhhhhhggp....',
  '.....pgrrrhhhhhhhhhhhhhrrrgp....',
  '......prrrrrrrrrrrrrrrrrrgp.....',
  '....ppprrrrrrrrrrrrrrrrrrrppp...',
  '...phhpphrrrrrrrrrrrrrrhpphhp...',
  '..phhhpphhprrrrrrrrrrphhpphhhp..',
  '..phhpp.phhprrrrrrrrphhp.pphhp..',
  '..phhp..phhpphhhhhhpphhp..phhp..',
  '..phhp..phhp.phhhhp.phhp..phhp..',
  '..phhp..phhp.phhhhp.phhp..phhp..',
  '..pphp..phhp.phpphp.phhp..php...',
  '...pp...phhp.php.php.phhp..pp...',
  '........phhp.php.php.phhp.......',
  '........pphp.php.php.phpp.......',
  '.........pp..ppp.ppp..pp........',
  '................................',
  '................................',
  '................................',
  '................................',
];

// c36 Kraken of the Undercroft: a giant squid rising, two arms raised, red-rimmed.
const krakenOfTheUndercroft = [
  '................................',
  '................................',
  '...............pp...............',
  '..............pghp..............',
  '..............pghp..............',
  '.............pgghhp.............',
  '.....pp......pgghhp......pp.....',
  '....p8hp....pggghhhp....ph8p....',
  '....p8hp....pggghhhp....ph8p....',
  '....phhp...pggghhhhhp...phhp....',
  '....phhp...pgggghhhhp...phhp....',
  '....phhp..pggggghhhhhp..phhp....',
  '....phhp..pggggghhhhhp..phhp....',
  '....phhp.pggghhhhhhhhhp.phhp....',
  '....phhp.pgpppghhhpppgp.phhp....',
  '....phhppgp88pghhp88pgppphhp....',
  '....phhhgp8jppghhp8jpgghhhhp....',
  '....pphhhgppphhhhhpppghhhpp.....',
  '.....ppphgggggggggggggppp.......',
  '.......pghhpghhpghhpghp.........',
  '......pghhpghhhpghhhpghhp.......',
  '......pghhpghhp.pghhpghhp.......',
  '.....pghhp.phhp.phhp.pghhp......',
  '.....pghhp.phhp.phhp.pghhp......',
  '.....phhp..phhp.phhp..phhp......',
  '....pghhp..php..php...phhp......',
  '....phhp...php..php...pphhp.....',
  '....phhp...pp....pp....phhp.....',
  '....pppp...............pppp.....',
  '................................',
  '................................',
  '................................',
];

// c53 Drowned Bride: a skeletal mermaid in a white veil, tail curling to the left.
const drownedBride = [
  '................................',
  '................................',
  '.............ppppp..............',
  '...........ppjjjjjpp............',
  '..........pjjkkkkkjjp...........',
  '.........pjjkkkkkkkjjp..........',
  '.........pjkkpkkpkkkjp..........',
  '.........pjkkppkppkkjp..........',
  '........pjjkkkkkkkkkjjp.........',
  '........pjjkpkpkpkpkjjp.........',
  '........pjj.ppppppp.jjp.........',
  '........pjj..pkkkp..jjp.........',
  '........pjj.pkkkkkp.jjp.........',
  '.......pjjppkpkpkpkpjjjp........',
  '.......pjj.pkkkkkkkp.jjp........',
  '.......pjj.pkpkpkpkp.jjp........',
  '.......pjj.pkkkkkkkp.jjp........',
  '.......pjj.ppkpkpkpp.jjp........',
  '........pp..phhhhhp..pp.........',
  '............phhhhgp.............',
  '...........phhhhhgp.............',
  '..........phhhhhgp..............',
  '.........phhhhhgp...............',
  '........phhhhhgp................',
  '.......phhhhhp..................',
  '.....pphhhhhp...................',
  '...pphhhihhp....................',
  '..phhhhhiphhhp..................',
  '..phhhhhp.phhp..................',
  '..pppppp..pppp..................',
  '................................',
  '................................',
];

// c54 Barnacle Abbot: a hooded abbot in a barnacled robe, holding a tall anchor.
const barnacleAbbot = [
  '................................',
  '................................',
  '................................',
  '.........ppppp..................',
  '........pgghhhp.......ppp.......',
  '.......pgghhhhhp.....plmlp......',
  '.......pghhhhhhp.....pl.lp......',
  '.......pggggggp.......plp.......',
  '.......pgigiggp.....ppplppp.....',
  '.......pgggggp......plllllllp...',
  '......pphhhhhpp.....ppplmppp....',
  '.....phhhhhhhhhp......plp.......',
  '....phhhkhhhhhhhp.....pmp.......',
  '....phhhhhhhkhhhhp....pmp.......',
  '...phhhhhhhhhhhhhhppppplp.......',
  '...phhkhhhhhhhhhhhhhhhplp.......',
  '...phhhhhhhhhhkhhhhhhhpmp.......',
  '...phhhhhhhhhhhhhhhhhhpmp.......',
  '...pghhhkhhhhhhhhhhhhppmp.......',
  '...pghhhhhhhhhhkhhhgp.pmp.......',
  '...pghhhhhhhhhhhhhhgp.pmp.......',
  '...pghhhkhhhhhhhhhhgp.pmp.......',
  '...pgghhhhhhhkhhhhggp.pmp.......',
  '...pgghhhhhhhhhhhhggp.pmpp......',
  '...pggghhhhkhhhhhgggpplmlpp.....',
  '...pggghhhhhhhhhhgggplllmlllp...',
  '...ppppppppppppppppppplmlppp....',
  '......................ppp.......',
  '................................',
  '................................',
  '................................',
  '................................',
];

// t_wisp: a small floating flame-ghost.
const wisp = [
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '..............pp................',
  '.............psjp...............',
  '............psjjsp..............',
  '............psjssp..............',
  '...........psjjsssp.............',
  '...........psjsssrp.............',
  '..........psjssssrp.............',
  '..........pssssssrp.............',
  '..........pspsspsrp.............',
  '..........pssssssrp.............',
  '...........psssrrp..............',
  '...........pssrpsp..............',
  '............prp.pp..............',
  '............pp..................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
];

// t_bat: a single small bat, wings spread.
const bat = [
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '.....pp................pp.......',
  '....pmmp..............pmmp......',
  '....pmnnp............pnnmp......',
  '...pmmnnnpp........ppnnnmmp.....',
  '...pmmmnnnnppppppppnnnnmmmp.....',
  '...pmmmmmmnnnpnnpnnnmmmmmmp.....',
  '....pmmmmmmmpipipmmmmmmmmp......',
  '.....pmmmppmmnnnnmppmmmmp.......',
  '......ppp..pnnnnnp..ppp.........',
  '...........pnpppnp..............',
  '...........pp..pp...............',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
];

// t_rubble: a low pile of grey stones.
const rubble = [
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '...........ppp..................',
  '..........plmmp.....ppp.........',
  '.......ppplmmmpp...plmmp........',
  '......plmmmmmmnnp.plmmmnp.......',
  '.....plmmmmmnnnnppmmmmnnnp......',
  '....plmmmppmmnnnmmmmmnnnnnp.....',
  '...plmmmmmnnppnmmmmppnnnnnpp....',
  '...pmmmmmnnnnnpmmmnnpnnnnnnnp...',
  '...pppppppppppppppppppppppppp...',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
];

// t_boneWall: a low wall of stacked bones with a skull set in the top course.
const boneWall = [
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '..............pppp..............',
  '.............pkkkkp.............',
  '.............pkpkpkp............',
  '..............pkkpp.............',
  '.....ppppppppppppppppppppppp....',
  '....pjkkkkkkkkjppjkkkkkkkkjp....',
  '....pjlllllllljppjlllllllljp....',
  '....pppppppppppppppppppppppp....',
  '......pjkkkkkkkkjppjkkkkkkkjp...',
  '......pjllllllllljppjlllllljp...',
  '......ppppppppppppppppppppppp...',
  '....pjkkkkkkkjppjkkkkkkkkkjp....',
  '....pjlllllljppjllllllllljp.....',
  '....pppppppppppppppppppppppp....',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
];

// t_chorister: a tiny hooded singer, mouth open.
const chorister = [
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '.............pppp...............',
  '............puuuup..............',
  '...........puuuuuup.............',
  '...........puvvvvup.............',
  '...........puvpvpvp.............',
  '...........puvvpvvp.............',
  '...........puvvpvvp.............',
  '...........puuvvvup.............',
  '..........puuuuuuuup............',
  '..........puuuuuuvup............',
  '..........puuuuuuvup............',
  '.........puuuuuuuvvup...........',
  '.........puuuuuuuvvup...........',
  '.........pppppppppppp...........',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
];

export const drownedSprites: SpriteDef[] = [
  { id: 'c25', rows: drownedArcher },
  { id: 'c26', rows: moray },
  { id: 'c27', rows: kelpWraith },
  { id: 'c28', rows: pearlDiver },
  { id: 'c29', rows: barnacleThrall },
  { id: 'c30', rows: brineChoir },
  { id: 'c31', rows: sirenOfVael },
  { id: 'c32', rows: rotPriest },
  { id: 'c33', rows: gloomJelly },
  { id: 'c34', rows: leviathanCalf },
  { id: 'c35', rows: motherOfSilt },
  { id: 'c36', rows: krakenOfTheUndercroft },
  { id: 'c53', rows: drownedBride },
  { id: 'c54', rows: barnacleAbbot },
  { id: 't_wisp', rows: wisp },
  { id: 't_bat', rows: bat },
  { id: 't_rubble', rows: rubble },
  { id: 't_boneWall', rows: boneWall },
  { id: 't_chorister', rows: chorister },
];
