import type { SpriteDef } from './types';

// The three elite enemies of Act I. Authored as code per docs/ART.md.
// Legend: p = outline (#181425), '.' = transparent; other characters index the Endesga 32 palette (see palette.ts).
// Bigger and more imposing than the rank-and-file enemies: each fills most of the 32×32 box inside the 2px padding.
// Bone k > steel l; teal h with navy g shadow; cyan i / white j water; moss d kelp; slate m > indigo n iron;
// fire 9 (orange) > a (amber) > b (gold); mauve s / plum r for the Abbot's song; bronze 3/1 for the censer.

// e_abbot The Choir Abbot: tall gaunt abbot, deep hood over a dark face with a glowing mauve mouth,
// one hand raised in benediction, a smoking bronze censer swinging from the other.
const e_abbot = [
  '................................',
  '................................',
  '..............pp................',
  '.............pkkp...............',
  '.............pkkp...............',
  '............pkkklp..............',
  '............pkkklp.....r........',
  '...........pkkooolp......r......',
  '...........pkoooolp...s.........',
  '..........pkkoooollp.s..........',
  '..........pkkoossolp..pkkp......',
  '..........pkkoorsolp..pkkp......',
  '..........pkkooooolp..pklp......',
  '...........pkkooolp..pkllp......',
  '..........pkkkkkkllppkllp.......',
  '.........pkkkkkkkkllllkllp......',
  '........pkkkkkkkkklllllllp......',
  '.......pkkkkkkkkkkllllllp.......',
  '......pkkpkkkkkkkklllllp........',
  '......pkkpkkkkkkkkllllp.........',
  '......pkkpkkkkkkkkllllp.........',
  '......pklpkkkkkkkkllllp.........',
  '......plppkkkkkkkklllllp........',
  '......p3p.pkkkkkkkklllllp.......',
  '......p1p.pkkkkkkkklllllp.......',
  '.....pp3pppkkkkkkkklllllp.......',
  '....p2331ppkkkkkkkkklllllp......',
  '....p3a1ppkkkkkkkkkkllllllp.....',
  '.....pppppkkkkkkkkkkllllllp.....',
  '.........pppppppppppppppppp.....',
  '................................',
  '................................',
];

// e_tideCaller The Tide-Caller: drowned priestess crowned with kelp, both arms raised,
// a tall wave curling over her from the right and foaming around her hem.
const e_tideCaller = [
  '................................',
  '................................',
  '................................',
  '.....................pjjjjp.....',
  '.........p.p.p....pjjjiiiihhgp..',
  '........pdpdpdp..pjjip.pgghhgp..',
  '........pdddddp..pjip..pgghhgp..',
  '........pkkkklp...pjp...pghhgp..',
  '...pkkp.pkikilp....p....pghhgp..',
  '...pkkp.pkkkklp..pkkp...pghhgp..',
  '...phgp.pkkkllp..pkkp...pihhgp..',
  '....phgp.pkllp..phgp...pihhhgp..',
  '.....phggghhhgggghgp...pihhigp..',
  '......pgghhhhhgggggp..pihhhhgp..',
  '.......pgghhhggggp....pihhhhgp..',
  '.......pgghhhggggp...pihhihhgp..',
  '.......pgghhhggggp...pihhhhhgp..',
  '......pgghhhhggggp..pihhhhihgp..',
  '......pgghhhhggggp..pihhhhhhgp..',
  '.....pgghhhhhggggp.piihhhhhhgp..',
  '.....pgghhhhhggggppjihhhhhhhgp..',
  '....pgghhhhhhggggpjiihhhhhhhgp..',
  '....pgghhhhhhggggpjjihhhhhhhgp..',
  '...pgghhhhhhhggggpjjjihhhhhhgp..',
  '...pgghhhhhhhggggpjjjjihhhhhgp..',
  '..pgghhhhhhhhggggppjjjjihhhhgp..',
  '..pgghhhhhhhhggggppjjjjjjihhgp..',
  '..pppppppppppppppppjjjjjjjjhgp..',
  '....piijjiijjiijjiijjiijjiijgp..',
  '.....pppppppppppppppppppppppp...',
  '................................',
  '................................',
];

// e_brazierKnight The Brazier Knight: hulking dark-iron knight, fire boiling out of a torn-open
// chest and licking through the visor slit, a flanged mace planted at its side.
const e_brazierKnight = [
  '................................',
  '................................',
  '.........................ppp....',
  '............ppppp.......pkllp...',
  '...........pm9mmnp.....pkllmmp..',
  '..........pm9amm9np....plllmnp..',
  '..........p9amma9np....pllmmnp..',
  '..........pabbba99p.....plmnp...',
  '..........pmmmmmnnp......ppp....',
  '..........pmmmmmnnp......plp....',
  '...........pmmmnnp.......plp....',
  '.........pmmmmmnnnnp.....plp....',
  '....plmmppmmmmmnnnnppnnnpplp....',
  '...plmmmppmmppppnnnppnnnnplp....',
  '...plmmmppmp9a9ppnnppnnnnplp....',
  '...pmmmnppp9aba9pnnppnnnnplp....',
  '....pmnp.p9abbba9pnp.pnnpplp....',
  '....pmnp.p9abba99pnp..pmnnnnp...',
  '....pmnp.pm9a999pnnp..pnnnnnp...',
  '....pmnp.pmp99ppnnnp..pnnnnnp...',
  '...pmmnnppmmppnnnnnp.....plp....',
  '...pmmnnppmmmmmnnnnp.....plp....',
  '....pppppmmmmmmnnnnnp...pmnnp...',
  '........pmmmmmmnnnnnp....ppp....',
  '........pmmnnp.pnnnnp...........',
  '........pmmnnp.pnnnnp...........',
  '........pmmnnp.pnnnnp...........',
  '.......pmmmnnp.pnnnnnp..........',
  '.......pmmmnnp.pnnnnnp..........',
  '.......ppppppp.ppppppp..........',
  '................................',
  '................................',
];

export const eliteSprites: SpriteDef[] = [
  { id: 'e_abbot', rows: e_abbot },
  { id: 'e_tideCaller', rows: e_tideCaller },
  { id: 'e_brazierKnight', rows: e_brazierKnight },
];
